# Generated by Django 3.2.2 on 2023-01-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
    ]
