# Generated by Django 3.2.2 on 2023-02-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='musclegroup',
            field=models.CharField(default='', max_length=70),
        ),
    ]
