# Generated by Django 3.2.2 on 2023-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_musclegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
